--- 
name: Ant 1.8.0 Source
platform_id: all
platform_version: all
distribution_file_uuid_string: openlogic-ant-1.8.0-all-src-1
platform_vendor: all
version_visibility: public
description: Ant 1.8.0 Source
platform_arch: all
distribution_file_uuid: 5a097af183a80195a02a35c864790995473ec5031974925b712e2940c1fb806d
distribution_version: 1
distribution_flavor: ""
distribution_raw_file: 1.8.0/apache-ant-1.8.0-src.tar.bz2
notify: "yes"
package_version: 1.8.0
package_id: ant
release_date: "2010-03-26"
distribution_notes: ""
distribution_type: src
